### ISSUE TITLE
"Contact Us" forms

### ISSUE THREAD

**Issue by BeckyBowers** [BeckyBowers/seaton#3]
"Contact Us" forms for Seaton and for the Seaton PTO.

**Comment by jeremyjbowers** [comment]
When people contact Seaton or the PTO, what are they doing? Do they want someone to write back? To answer random questions? What is our model behavior we want from a user?

**Comment by jeremyjbowers** [comment]
Contact forms are just a page type. This isn't hard -- what's hard is deciding which behaviors to hint and which behaviors to discourage.

**Comment by BeckyBowers** [comment]
Let's use seatonpto@gmail.com for PTO page. I don't have final confirmation from Shereen, but that's the one Ericka thought it would be.

**Comment by jeremyjbowers** [comment]
Looks like email is not important -- these will just point internally to the site and we get it in a "feedback" bucket.
